##
# @author Luca-Philipp Grumbach, Richard Hofmann
# @section DESCRIPTION
# Build the documentation using GitHub Actions.
##
name: Build documentation

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:

    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run: cd docs
        && make html
        && cd build/html
        && touch .nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy.
