##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches:    
      - 'develop'
      - 'main'
      - 'gui_develop'

  pull_request:
    branches:    
      - 'develop'
      - 'main'
      - 'gui_develop'

  schedule:
    - cron: 0 0 * * *

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons
          sudo apt-get install valgrind
          sudo apt-get install cppcheck
          sudo apt-get install libnetcdf-dev
          sudo apt-get install libomp-dev
          git submodule init
          git submodule update

      - name: Static Code Analysis
        run:
          cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: Sanitize
        run: |
          scons mode=debug+san omp=gnu gui=no
          ./build/tests
          ./build/tsunami_lab configs/minimalConfig.json
          scons mode=release+san omp=gnu gui=no
          ./build/tests
          ./build/tsunami_lab configs/minimalConfig.json

      - name: Valgrind
        run: |
          scons mode=debug omp=gnu gui=no
          valgrind ./build/tests
          valgrind ./build/tsunami_lab configs/minimalConfig.json

      - name: Release
        run: |
          scons omp=gnu gui=no
          ./build/tests
          ./build/tsunami_lab configs/minimalConfig.json
